### ISSUE TITLE
Install issue w/ ember-cli 2.10 and 2.14

### ISSUE THREAD

**Issue by dirkdirk** [stefanpenner/ember-moment#255]
Created a new ember app to test with the following:

```
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^2.4.1",
    "ember-cli": "2.14.1",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-babel": "^5.1.7",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-htmlbars": "^1.0.10",
    "ember-cli-htmlbars-inline-precompile": "^0.3.3",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-jshint": "^2.0.1",
    "ember-cli-moment-shim": "3.4.0",
    "ember-cli-qunit": "^3.0.1",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.10.0",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-moment": "7.4.1",
    "ember-resolver": "^2.0.3",
    "ember-welcome-page": "^1.0.3",
    "loader.js": "^4.0.10"
  },
```

Run ember server and get the following with both ember-cli 2.14.1 and 2.10.0:

```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger: `addon/` trees] failed with:
TypeError: The plugin [null,{"envFlags":{"source":"@glimmer/env","flags":{"DEBUG":true,"CI":false}},"externalizeHelpers":{"global":"Ember"},"debugTools":{"source":"@ember/debug","assertPredicateIndex":1}}] didn't export a Plugin instance
    at PluginManager.validate (/Users/Dirk/www/test-ember/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/Dirk/www/test-ember/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/Dirk/www/test-ember/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/Dirk/www/test-ember/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/Dirk/www/test-ember/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at /Users/Dirk/www/test-ember/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:102:26
    at initializePromise (/Users/Dirk/www/test-ember/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/Users/Dirk/www/test-ember/node_modules/rsvp/dist/rsvp.js:1039:33)
    at Object.transformString (/Users/Dirk/www/test-ember/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:101:12)
    at Babel.transform (/Users/Dirk/www/test-ember/node_modules/broccoli-babel-transpiler/index.js:110:22)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/Dirk/www/test-ember/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/Dirk/www/test-ember/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/Users/Dirk/www/test-ember/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:10:53)
    at mergeTrees (/Users/Dirk/www/test-ember/node_modules/ember-cli/lib/broccoli/merge-trees.js:85:33)
    at EmberApp._mergeTrees (/Users/Dirk/www/test-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1815:12)
    at EmberApp._addonTree (/Users/Dirk/www/test-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:958:36)
    at EmberApp._processedExternalTree (/Users/Dirk/www/test-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1009:25)
    at EmberApp.appAndDependencies (/Users/Dirk/www/test-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1119:25)
    at EmberApp.javascript (/Users/Dirk/www/test-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1235:30)
    at EmberApp.toArray (/Users/Dirk/www/test-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1672:12)
```

Not sure what to try next.

**Comment by jasonmit** [comment]
Cannot reproduce with a fresh install of ember-cli and ember-moment/ember-cli-moment-shim.  If you can throw together an example that reproduces please reopen.

**Comment by dirkdirk** [comment]
Finally got back to this.  

A re-install all the node modules fixed it: delete `./node_modules` then `$ npm install`
