### ISSUE TITLE
Cannot find module './key-for-file'

### ISSUE THREAD

**Issue by juliankmazo** [stefanpenner/ember-moment#71]
I'm getting this error after install. 
I have installed ember cli 1.13.1, and ember 1.12.1
Help :confounded: 
```
ember s
Cannot find module './key-for-file'
Error: Cannot find module './key-for-file'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/julian/Developer/work/freelancing/cvc-portal-livelo-ui/node_modules/ember-moment/node_modules/broccoli-stew/node_modules/cauliflower-filter/filter.js:14:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by netoho** [comment]
Same happen to me

**Comment by stefanpenner** [comment]
fixed

**Comment by juliankmazo** [comment]
Thanks @stefanpenner :laughing:
