### ISSUE TITLE
Can't install addon. Error: Cannot read property 'reduce' of undefined?

### ISSUE THREAD

**Issue by mattmazzola** [stefanpenner/ember-moment#79]
Hi,

After I upgraded to ember-cli 1.13.5 I cannot get ember-moment to install.  I've used ember-moment before with previous projects and I assume this addon still works for other people so it must be an environmental thing, but I want to ask if there is a known work around for this type of issue?

I'm running on windows if that makes a difference.
```
ember install ember-moment
version: 1.13.5
Installed packages for tooling via npm.
installing ember-moment
  install addon ember-cli-moment-shim
Installed packages for tooling via npm.
Cannot read property 'reduce' of undefined
TypeError: Cannot read property 'reduce' of undefined
    at Class.module.exports.Task.extend.installBlueprint (C:\embercli\studentdashboard\client\node_modules\ember-cli\lib\tasks\addon-install.js:54:24)
    at Class.<anonymous> (C:\embercli\studentdashboard\client\node_modules\ember-cli\lib\tasks\addon-install.js:43:19)
    at lib$rsvp$$internal$$tryCatch (C:\embercli\studentdashboard\client\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (C:\embercli\studentdashboard\client\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (C:\embercli\studentdashboard\client\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:476:11)
    at lib$rsvp$asap$$flush (C:\embercli\studentdashboard\client\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at process._tickCallback (node.js:340:13)
```

**Comment by jasonmit** [comment]
https://github.com/stefanpenner/ember-moment/issues/72
